version: "3"

services:
  mysql-server:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    networks:
      - local-dev
    environment:
#      MYSQL_DATABASE: "products"
      MYSQL_USER: "aplicacao"
      MYSQL_PASSWORD: "aplicacao"
      MYSQL_ROOT_PASSWORD : "root"
    volumes:
      - ./volumes/mysql:/var/lib/mysql
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
  rabbitmq:
    image: rabbitmq:3-management
    restart: "no"
    ports:
      - 15672:15672
      - 5672:5672
  mongo:
    image: mongo
    ports:
      - 27017:27017
networks:
  local-dev:
    driver: bridge