spring:
  application:
    name: products-query
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false
        retry:
          enabled: false
          max-attempts: 3
          initial-interval: 1000
          multiplier: 2
          max-interval: 5000
  data:
    mongodb:
      uri: mongodb://localhost:27017/products
      auto-index-creation: true

server:
  servlet:
    context-path: /products-query
  port: 8081
