version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: "no"
    ports:
      - 15672:15672
      - 5672:5672
  mongo:
    image: mongo
    ports:
      - 27017:27017
networks:
  local-dev:
    driver: bridge